FROM multiarch/qemu-user-static:x86_64-arm as qemu
FROM arm32v7/python:3.7-alpine
MAINTAINER Christophe Lambin <christophe.lambin@gmail.com>

COPY --from=qemu /usr/bin/qemu-arm-static /usr/bin

WORKDIR /app

EXPOSE 8080
RUN addgroup -S -g 1000 abc && \
    adduser -S --uid 1000 --ingroup abc abc
RUN pip install --upgrade pip && \
    pip install pipenv
COPY Pip* ./
RUN pipenv install --system --deploy --ignore-pipfile
COPY *.py ./

USER abc
ENTRYPOINT ["/usr/local/bin/python3", "covid19mon.py"]
CMD []
