FROM multiarch/qemu-user-static:x86_64-aarch64 as qemu
FROM arm64v8/python:3.7-slim
MAINTAINER Christophe Lambin <christophe.lambin@gmail.com>

COPY --from=qemu /usr/bin/qemu-aarch64-static /usr/bin

WORKDIR /app

EXPOSE 8080
RUN groupadd -g 1000 abc && \
    useradd -u 1000 -g abc abc && \
    pip install --upgrade pip && \
    pip install pipenv && \
    echo "[global]" >> /etc/pip.conf && \
    echo "extra-index-url=https://www.piwheels.org/simple" >> /etc/pip.conf
COPY Pip* ./
RUN pip install psycopg2-binary && \
    pipenv install --system --deploy --ignore-pipfile
COPY *.py ./
COPY src/*.py ./src/

USER abc
ENTRYPOINT ["/usr/local/bin/python3", "covid19.py"]
CMD []
