{
 "title": "Corona",
 "time": { "from": "now-14d", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "country", "query": "label_values(name)" }
  ]
 },
 "panels": [
  { "title": "Country", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "corona_death_count{name=\"$country\"}",
     "legendFormat": "Death"
    },
    {
     "expr": "corona_recovered_count{name=\"$country\"}",
     "legendFormat": "Recovered"
    },
    {
     "expr": "corona_confirmed_count{name=\"$country\"}-corona_death_count{name=\"$country\"}-corona_recovered_count{name=\"$country\"}",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Ratio over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(corona_confirmed_count{name=~\"$country\"}-corona_death_count{name=~\"$country\"}-corona_recovered_count{name=~\"$country\"})/corona_confirmed_count{name=~\"$country\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "corona_death_count{name=~\"$country\"}/corona_confirmed_count{name=~\"$country\"}",
     "legendFormat": "Deaths"
    },
    {
     "expr": "corona_recovered_count{name=~\"$country\"}/corona_confirmed_count{name=~\"$country\"}",
     "legendFormat": "Recovered"
    }
   ]
  },
  {
   "title": "Cases (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "corona_confirmed_count{name=~\"$country\"}-corona_death_count{name=~\"$country\"}-corona_recovered_count{name=~\"$country\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "corona_death_count{name=~\"$country\"}",
     "legendFormat": "Deaths"
    },
    {
     "expr": "corona_recovered_count{name=~\"$country\"}",
     "legendFormat": "Recovered"
    }
   ]
  },
  {
   "title": "New Cases / Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(corona_confirmed_count{name=~\"$country\"}[1d])",
     "legendFormat": "Confirmed"
    },
    {
     "expr": "delta(corona_death_count{name=~\"$country\"}[1d])",
     "legendFormat": "Deaths"
    },
    {
     "expr": "delta(corona_recovered_count{name=~\"$country\"}[1d])",
     "legendFormat": "Recovered"
    }
   ]
  },
  {
   "title": "Cases (stacked; log10)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "corona_death_count{name=~\"$country\"}",
     "legendFormat": "Deaths"
    },
    {
     "expr": "corona_recovered_count{name=~\"$country\"}",
     "legendFormat": "Recovered"
    },
    {
     "expr": "corona_confirmed_count{name=~\"$country\"}-corona_death_count{name=~\"$country\"}-corona_recovered_count{name=~\"$country\"}",
     "legendFormat": "Active"
    }
   ]
  }
 ]
}