{
 "title": "Corona - World",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "World Map (active)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (country) (corona_confirmed_count - corona_death_count - corona_recovered_count)",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "World Map (total)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (country) (corona_confirmed_count) ",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(corona_death_count)", "legendFormat": "Death" },
    { "expr": "sum(corona_recovered_count)", "legendFormat": "Recovered" },
    {
     "expr": "sum(corona_confirmed_count)-sum(corona_death_count)-sum(corona_recovered_count)",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Ratio over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(corona_confirmed_count)-sum(corona_death_count)-sum(corona_recovered_count))/sum(corona_confirmed_count)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(corona_death_count)/sum(corona_confirmed_count)",
     "legendFormat": "Death"
    },
    {
     "expr": "sum(corona_recovered_count)/sum(corona_confirmed_count)",
     "legendFormat": "Recovered"
    }
   ]
  },
  {
   "title": "Cases (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(corona_confirmed_count)-sum(corona_death_count)-sum(corona_recovered_count)",
     "legendFormat": "Active"
    },
    { "expr": "sum(corona_death_count)", "legendFormat": "Death" },
    { "expr": "sum(corona_recovered_count)", "legendFormat": "Recovered" }
   ]
  },
  {
   "title": "New Cases / Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(delta(corona_confirmed_count[1d]))",
     "legendFormat": "Confirmed"
    },
    {
     "expr": "sum(delta(corona_death_count[1d]))",
     "legendFormat": "Deaths"
    },
    {
     "expr": "sum(delta(corona_recovered_count[1d]))",
     "legendFormat": "Recovered"
    }
   ]
  },
  {
   "title": "Cases (stacked; log10)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(corona_death_count)", "legendFormat": "Death" },
    { "expr": "sum(corona_recovered_count)", "legendFormat": "Recovered" },
    {
     "expr": "sum(corona_confirmed_count)-sum(corona_death_count)-sum(corona_recovered_count)",
     "legendFormat": "Active"
    }
   ]
  }
 ]
}