{
 "title": "Covid19 - World",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Ratio over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(confirmed-death-recovered) AS \"active\",\n  sum(death) AS \"death\",\n  sum(recovered) AS \"recovered\"\nFROM covid19\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  confirmed-death-recovered \"active\",\n  death,\n  recovered\nFROM covid19\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "New Cases / Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  day as \"time\",\n  sum(confirmed) as \"confirmed\",\n  sum(death) as \"death\",\n  sum(recovered) as \"recovered\"\nFROM delta\nWHERE\n  $__timeFilter(\"day\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Confirmed cases by country",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  country_name,\n  confirmed\nFROM covid19\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Death toll by country",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  country_name,\n  death\nFROM covid19\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  { "title": "Maps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "World Map - Total Cases",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  country_code,\n  confirmed\nFROM covid19\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "World Map - Cases / Population",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 23 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  a.time as \"time\", \n  a.country_code,\n  CAST (100.0 * a.confirmed / b.population AS FLOAT) AS \"confirmed\"\nFROM covid19 a, population b \nWHERE \n  a.country_code = b.country_code and\n  $__timeFilter(\"time\")\nORDER BY 1,2;"
    }
   ]
  },
  {
   "title": "World Map - Active",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 36 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  country_code,\n  confirmed-recovered-death \"active\"\nFROM covid19\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "World Map - Evolution",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 36 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1d),\n  country_code as \"metric\",\n  avg(confirmed-death-recovered) - lag(avg(confirmed-death-recovered)) OVER (PARTITION by country_code ORDER BY $__timeGroup(\"time\",1d)) AS \"value\"\nFROM covid19\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1, metric\nORDER BY 1, metric"
    }
   ]
  },
  {
   "title": "World Map - Deaths",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 49 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  country_code,\n  death\nFROM covid19\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}