name: Flake

on: [push, pull_request]

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: flake8
        run: |
          pip install flake8
          flake8 --max-line-length 120