name: SAST

on: [push, pull_request]

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: SAST
        run: |
          pip install safety bandit
          safety check
          bandit -r -x ./tests .