name: Test

on:
  push:
    branches-ignore:
      - master
      - develop
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.7
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Test with pytest
      run: |
        export POSTGRES_HOST=postgres
        export POSTGRES_PORT=5432
        export POSTGRES_DB=postgres
        export POSTGRES_USER=postgres
        export POSTGRES_PASSWORD=postgres
        export API_KEY=${{ secrets.API_KEY }}
        cd tests && pipenv run pipenv run pytest --cov=.. --cov-report=xml
    - uses: codecov/codecov-action@v1
      with:
        file: tests/coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}