name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    - closed

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.7
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: flake8
      run: |
        flake8 --max-line-length 120-
    - name: SAST
      run: |
        safety check
        bandit -r -x ./tests .
    - name: Test with pytest
      run: |
        export POSTGRES_HOST=postgres
        export POSTGRES_PORT=5432
        export POSTGRES_DB=postgres
        export POSTGRES_USER=postgres
        export POSTGRES_PASSWORD=postgres
        export API_KEY=${{ secrets.API_KEY }}
        cd tests && pipenv run pipenv run pytest --cov=.. --cov-report=xml
    - uses: codecov/codecov-action@v1
      with:
        file: tests/coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
  build-covid19mon:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: metadata for covid19mon
      id: docker_meta_mon
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        tag-sha: true
        images: clambin/covid19mon
    - name: Build and push covid19mon
      id: docker_build_mon
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta_mon.outputs.tags }}
        labels: ${{ steps.docker_meta_mon.outputs.labels }}
  build-covid19api:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker meta covid19api
      id: docker_meta_api
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        tag-sha: true
        images: clambin/covid19api
    - name: Build and push covid19api
      id: docker_build_api
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-covid19api
        platforms: linux/amd64,linux/arm
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta_api.outputs.tags }}
        labels: ${{ steps.docker_meta_api.outputs.labels }}
  deploy:
    needs: [build-covid19mon, build-covid19api]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
    - uses: actions/checkout@v2
    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - name: get tag
      id: image_tag
      run: echo "::set-output name=sha_short::sha-$(echo ${GITHUB_SHA} | cut -c1-7)"
    - name: debug
      run: |
        echo "${GITHUB_SHA}"
        echo "${{ steps.image_tag.outputs.sha_short }}"
    - uses: Azure/k8s-deploy@v1
      with:
        namespace: default
        manifests: |
          manifests/covid19-deployment.yml
        images: |
          clambin/covid19mon:${{ steps.image_tag.outputs.sha_short }}
          clambin/covid19api:${{ steps.image_tag.outputs.sha_short }}
        force: true